root: true # Корневой уровень правил
env:
  browser: true # browser global variables TODO - в папку скриптов
  jquery: true #  jQuery global variables TODO - в папку скриптов
  es6: true # enable all ECMAScript 6 features except for modules
  node: true # Node.js global variables and Node.js scoping
  # mongo: true # MongoDB global variables Не понятно нужно ли
globals:
  app: true
  # var2: false
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6 # specify the version of ECMAScript
  sourceType: module
rules: # Описание правил https://eslint.org/docs/rules/
  # Possible Errors
  for-direction: error # Недостижимые циклы for - Откл.в recommended
  getter-return: error # Геттеры не содержат return - Откл.в recommended
  no-await-in-loop: error # Await в циклах - не позволяет запустить в них код асинхронно. Лучше Promise.all - Откл.в recommended
  no-console: warn # Использование консольного вывода в продакшене не рекомендуется - Изм.recommended: error
  no-prototype-builtins: warn # Использование вызовов метода Object.prototype в объекте - Изм.recommended: error
  no-template-curly-in-string: warn # Использование шаблонов не в кавчках ` - Откл.в recommended
  valid-jsdoc: # Валдиация jsDoc - Откл.в recommended
    - warn
    - {requireReturn: false, # Не требуем обязательный return
      requireReturnType: true, # Требуется тип возвращаемого значения
      requireParamDescription: true, # Требуется описание параметра
      requireReturnDescription: true} # Требуется описание возвращаемого значения

  # Best Practices -
  accessor-pairs: warn # Обязательность и сеттера и геттера в объекте, если есть хоть один - Откл.в recommended
  array-callback-return: warn # Обязательность куегкт или калбека в методах массива - Откл.в recommended
  block-scoped-var: warn # Использование переменной вне блока объявления - Откл.в recommended
  class-methods-use-this: warn # Методы не использующие this - должны объявляться static - Откл.в recommended
  complexity: # Цикломатическая сложность - т.е. кол-во веток/путей в функции
    - warn
    - 10 # В jshint было 10 (рек. в wiki) - recommended: 20
  consistent-return: warn # Требование значение для функции return - Откл.в recommended
  curly: error # Требования обязательно наличия скобок - Откл.в recommended
  default-case: error # Обязательный default в switch - Откл.в recommended
  dot-location: # Размещение точки - Откл.в recommended
    - warn
    - property # Если с новой строки, то перед свойством
  dot-notation: warn # Использовать точки для доступа к свойстам, вместо нотации именнованного массива - Откл.в recommended
  eqeqeq: warn # Строгое сравнение с типами, без приведения - Откл.в recommended
  guard-for-in: warn # Проверка на свойство в циклах for-in - Откл.в recommended
  no-caller: error # Запрет на caller - выводится из JS  - Откл.в recommended
  no-div-regex: error # Требование экранирования литералов regexp - Откл.в recommended
  no-else-return: warn # Не требуется else с return - Откл.в recommended
  no-empty-function: warn # Запрет пустых функций (нужен хотя бы комментарий) - Откл.в recommended
  no-eq-null: error # Запрет на сравнение с нулем без приведения типов  - Откл.в recommended
  no-eval: error # Запрет на eval - Откл.в recommended
  no-extend-native: error # Запрет на изменение свойств и методов нативных объектов - Откл.в recommended
  no-extra-bind: error # Использование bind без this - Откл.в recommended
  no-extra-label: error # Запрет использовани ярасширенных меток - Откл.в recommended
  no-floating-decimal: error # Запрет чисел с плав.точкой без числа перед точкой - Откл.в recommended
  no-implicit-coercion: warn # Запрет на неявные преобразования типов - Откл.в recommended
  no-implied-eval: error # Запрет на неявный вызов eval - Откл.в recommended
  no-invalid-this: error # Запрет на this вне классов и подобных объектов - Откл.в recommended
  no-labels: error # Запрет использования меток - Откл.в recommended
  no-lone-blocks: error # Запрет на пустые кривые скобки - Откл.в recommended
  no-loop-func: warn # Создание функций внутри циклов или функций исп. переменную вне обл.видимости - Откл.в recommended
  no-magic-numbers: warn # Использование цифровых констант 2*5*100 в присвоении - Откл.в recommended
  no-multi-spaces:  # Использование пробелов оформления - Откл.в recommended
    - warn
    - ignoreEOLComments: true # За исключением комментариев
  no-multi-str: error # Запрет на мультистроки - Откл.в recommended
  no-new: error # Запрет на конструкт, без присваивания результатов - Откл.в recommended
  no-new-func: error # Запрет на использования конструктора функций - Откл.в recommended
  no-new-wrappers: error # Запрет на конструктор объектов JS - Откл.в recommended
  no-octal-escape: error # Запрет на восмеричное исчисление через esc последовательность - Откл.в recommended
  # no-param-reassign: warn # Запрет изменения параметров функций - нужно присваивание новым переменным - ошибка если использовать arguemnt[] (не надо использовать argument[] )))) - Откл.в recommended
  no-proto: error # Запрещенная свойство Object - Откл.в recommended
  no-return-assign: warn # Запрет присваивание в return - Откл.в recommended
  no-return-await: error # Запрет на возврат async в return - Откл.в recommended
  no-self-compare: error # Запрет на сравнение с самим собой - Откл.в recommended
  no-sequences: error # Запрет на использование нескольких выражений через запятую - Откл.в recommended
  no-throw-literal: warn # Запрет на неявное создание объекта Error в throw - Откл.в recommended
  no-unmodified-loop-condition: error # Запрет использования немодифицируемых условий в циклах - Откл.в recommended
  no-unused-expressions: warn # Запрет на неиспользуемые выражения - Откл.в recommended
  no-useless-call: warn # Запрет на неоптимальный вызов call и apply - Откл.в recommended
  no-useless-concat: warn # Запрет на склеивание строк констант - Откл.в recommended
  no-useless-return: warn # Запрет на путсые операнды в return - Откл.в recommended
  no-void: error # Запрет на устаревший тип void - Откл.в recommended
  no-warning-comments: # Предупреждения, для разработческих комментов для продуктива - Откл.в recommended
    - warn
    - {"terms": ["todo", "fixme", "xxx", "2del"], "location": "anywhere" }
  no-with: error # Запрет использования with - Откл.в recommended
  prefer-promise-reject-errors: warn # Предупреждение использования приведения к Error для reject - Откл.в recommended
  radix: error # Требования указания исчисления для parseInt, если строка с 0 - Откл.в recommended
  require-await: error # Требование await в async функциях  - Откл.в recommended
  vars-on-top: warn # Требование расположения объявлений var вверху функций - Откл.в recommended
  wrap-iife: error # Оформление скобками немедленный вызов функций при объявлении - Откл.в recommended
  yoda: warn # Предупреждение при yoda сравнениях 5 > abc или 'текст' === strVal - Откл.в recommended
  strict: warn # Обязательный strict режим - Откл.в recommended
  # Variables
  no-label-var: error
  no-restricted-globals: # Запрещено использовать нижеследующие глобальные переменные - Откл.в recommended
    - error
    - event # Глобальную переменную even в IE
  no-shadow: # Запрет на повторяющеся объявление переменных выще видимсти
    - warn
    - {"builtinGlobals": true,  # Запрет переприсваивания глобальных переменных
       "hoist": "all",  # Запрет переобъявления с таким же именем везде
       "allow": [] } # Нет исключений
  no-shadow-restricted-names: error # Запрет переопределения типов стандарта JS
  no-undef-init: error # Запрет инициализации переменной как неопределена присваиванием undefined
  no-undefined: warn # Предупрежение переопределения или сравнения с undefined
  no-use-before-define: # Запрет на использование переменной, раньше объявления
    - error
    - functions: false # За исключением функций

  # Node.js and CommonJS
  callback-return: # Требует return для калбеков с ошибками, для исключения множественных вызовов. Можно использовать другие названия функций, или поставить изменение правил
    - warn
    - ["callback", "cb", "next", "done"] # Типовые названия функций клабеков
  global-require: # Глобальное размещение require в моделях - для упрощения отслеживания зависимостей
    - warn
  handle-callback-err: # Рекомендация шаблона калбека с первой err
    - warn
  no-buffer-constructor: # Предупреждение использования контруктора буффера
    - warn
  no-mixed-requires:
    - error # Запрет на смешение require ядра, модулей и переменных
  no-new-require: # Запрет на вызов конструктора при подключении модуля
    - error
  no-path-concat: # Предупреждение использования склеивания строк с глобалными переменными пути, без испльзования библиотеки path
    - warn
  no-process-env: # Предупреждение при конфигурировании приложения через переменные окружения, лучше через конфиг
    - warn
  no-process-exit: # Запрет на выход из приложения через process.exit
    - error
  no-restricted-modules: # Предупреждение при использовании запрещенных модулей
    - warn
    - {
        "paths": [ # Запрещенные библиотеки - как fs, js-zip и т.п.
          {"name": "lib/convert-import-util", "message": "Библиотека импорта вывдена в node_modules"},
          {"name": "async", "message": "Библиотека async использует имя из ES6"}
        ],
        "patterns": ["/lib/meta-update/*"] # Запрет на паттерны
      }
  no-sync: # Запрет на синхронные функции в продакшн коде
    - error
  # Stylistic Issues
  array-bracket-newline: # Новая линия после скобок в массивах запрещена
    - warn
    - never
  array-bracket-spacing: # Пробел после и перед скобками в массиве запрещены
    - warn
    - never
  array-element-newline: # Новая строка перед каждым элементом массива запрещены
    - warn
    - never
  block-spacing: # Пробел перед каждым блоком запрещены
    - warn
    - never
  brace-style: # Тип скобок - стандартный, разрешены на одной строке
    - warn
    - 1tbs
    - allowSingleLine": true
  camelcase: # Стиль камелКейс, в т.ч. для свойств объектов
    - warn
  capitalized-comments:
    - warn
    - always
    - ignoreInlineComments: true
    - ignoreConsecutiveComments: true
  comma-dangle: # Запрет запяты в конце в массивах, объектах, функциях и т.д.
    - error
    - never
  comma-spacing: # Пробел после запятых
    - warn
    - {"before": false, "after": true}
  comma-style: # Запятые в конце строки
    - warn
  computed-property-spacing: # Пробелы перед/после имени свойства объекта в кв.скобках
    - warn
    - never
  consistent-this: # Присваивание this только одному имени _this
    - error
    - _this
  eol-last: # Новая строка в окончании файла
    - warn
    - always
  func-call-spacing: # Пробел перед вызовом функции
    - warn
    - never
  func-name-matching: # Запрет на переприсваивание имени функций переменной с другим именем
    - error

  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  require-jsdoc:
    - warn
    - require: {FunctionDeclaration: true, # Определение функций
                MethodDefinition: false, # Определение методов
                ClassDeclaration: true, # Определения классов
                ArrowFunctionExpression: false, # Стрелочные выражения - объявление стрелочной функции в контексте выражения
                FunctionExpression: true} # Функциональные выражение var f = function - объявление функции в контексте какого-либо выражения

  # ECMAScript 6



