image: docker.iondv.ru/kube/docker/pygitlab:master
stages:
    - create
    - check
    - semver
.create: &JobCreate
  type: create
  tags:
    - dapp
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/create_pipelines_stages.sh | bash
  artifacts:
    name: "$CI_JOB_STAGE_$CI_BUILD_REF_NAME"
    expire_in: 1 week 
    when: on_success
    untracked: true
  allow_failure: false
  when: manual
.check: &JobCheck
  type: check
  tags:
    - kube-deploy
  before_script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/stage_access.sh | bash
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/check_pipelines_stages.sh | bash
  variables:
    GIT_STRATEGY: none
  when: manual
  allow_failure: false
.semver: &JobSemver
  type: semver
  only:
    - develop
  tags:
    - kube-deploy
  before_script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/stage_access.sh | bash
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/autoversion.sh | bash
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/push_autover.sh | bash
  when: manual
  allow_failure: true
Create:
  <<: *JobCreate
  only:
    - branches
Check:
  <<: *JobCheck
  only:
    - branches
  dependencies:
    - Create
Patch:
  <<: *JobSemver
Minor:
  <<: *JobSemver
Major:
  <<: *JobSemver