image: docker.iondv.ru/kube/docker/pygitlab:master
before_script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/stage_access.sh | bash
stages:
    - semver
    - create
    - check
    - autover
.semver: &JobSemver
  type: semver
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/autoversion.sh | bash
  when: manual
  artifacts:
    name: "$CI_JOB_STAGE_$CI_BUILD_REF_NAME"
    expire_in: 1 week 
    when: on_success
    untracked: true    
.create: &JobCreate
  type: create
  tags:
    - dapp
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/create_pipelines_stages.sh | bash
  allow_failure: false
  when: manual
  artifacts:
    name: "$CI_JOB_STAGE_$CI_BUILD_REF_NAME"
    expire_in: 1 week 
    when: on_success
    untracked: true
.check: &JobCheck
  type: check
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/check_pipelines_stages.sh | bash
  when: manual
  environment:
    name: testing/$CI_COMMIT_REF_SLUG
    url: http://${CI_COMMIT_REF_SLUG}.develop-and-test.kube.local
    #on_stop: Delete
  variables:
    GIT_STRATEGY: none
  allow_failure: false
.del: &JobDelete
  type: delete
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/delete_pipelines_stages.sh | bash
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: testing/$CI_COMMIT_REF_SLUG
    action: stop
.pushver: &JobPushVer
  type: autover
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/push_autover.sh | bash
  allow_failure: false
  when: on_success
Create:
  <<: *JobCreate
  only:
    - branches
Check:
  <<: *JobCheck
  only:
    - branches
  dependencies:
    - Create
Patch:
  <<: *JobSemver
  only:
    - develop
Minor:
  <<: *JobSemver
  only:
    - develop
Major:
  <<: *JobSemver
  only:
    - develop
Push version:
  <<: *JobPushVer
  only:
    - develop
  dependencies:
    - Patch
    - Minor
    - Major