image: docker.iondv.ru/kube/docker/pygitlab:master
stages:
    - create
    - check
    - delete
.create: &JobCreate
  type: create
  tags:
    - dapp
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/create_pipelines_stages.sh | bash
  allow_failure: false
  variables:
    GIT_STRATEGY: none
  when: manual
  artifacts:
    name: "$CI_JOB_STAGE_$CI_BUILD_REF_NAME"
    expire_in: 1 mos
    when: on_success
    untracked: true
.check: &JobCheck
  type: check
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/check_pipelines_stages.sh | bash
  environment:
    name: testing/$CI_COMMIT_REF_SLUG
    url: http://${CI_COMMIT_REF_SLUG}.develop-and-test.kube.local
    on_stop: Delete
  variables:
    GIT_STRATEGY: none
  when: manual
  allow_failure: false
.del: &JobDelete
  type: delete
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/delete_pipelines_stages.sh | bash
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: testing/$CI_COMMIT_REF_SLUG
    action: stop
Create:
  <<: *JobCreate
  only:
    - branches
Check:
  <<: *JobCheck
  only:
    - branches
  dependencies:
    - Create
Delete:
  <<: *JobDelete
  only:
    - branches
  dependencies:
    - Create