Testing ion-portal(master):
  type: test
  tags:
    - master-selenium
  only:
    - master
  script:
    - cmd /c mklink /D node_modules "$Env:RUNNER_PATH\node_modules"
    - $env:NODE_PATH = pwd
    - npm install
    - gulp build
    - start-job -ScriptBlock {node bin/www} -InitializationScript {cd "$Env:RUNNER_PATH\$Env:CI_PROJECT_DIR"} -Name $Env:PJ_DOCKER_NAME_MASTER
    - gulp test
Testing ion-portal(develop):
  type: test
  tags:
    - dev-selenium
  only:
    - develop
  script:
    - cmd /c mklink /D node_modules "$Env:RUNNER_PATH\node_modules"
    - $env:NODE_ENV = "development"
    - $env:NODE_PATH = pwd
    - npm install
    - gulp build
    - start-job -ScriptBlock {node bin/www} -InitializationScript {cd "$Env:RUNNER_PATH\$Env:CI_PROJECT_DIR"} -Name $Env:PJ_DOCKER_NAME_DEV
    - gulp test
"http://docker.local:8000 ion-portal":
  type: deploy
  tags:
    - docker
  only:
    - master
  script:
    - sudo docker stop $PJ_DOCKER_NAME_MASTER
    - ln -s /docker/node_modules/ node_modules
    - npm install
    - export NODE_PATH=`pwd -P`
    - export ION_INIT_DB=drop
    - gulp build
    - gulp docker
    - cd docker
    - sudo docker cp ./ $PJ_DOCKER_NAME_MASTER:/var/www
    - sleep 3
    - sudo docker start $PJ_DOCKER_NAME_MASTER
"http://docker.local:3000 ion-portal":
  type: deploy
  tags:
    - dev-docker
  only:
    - develop
  script:
    - sudo docker stop $PJ_DOCKER_NAME_DEV
    - ln -s /docker/node_modules/ node_modules
    - npm install
    - export NODE_PATH=`pwd -P`
    - export NODE_ENV=development
    - export ION_INIT_DB=drop
    - gulp build
    - gulp docker
    - cd docker
    - sudo docker cp ./ $PJ_DOCKER_NAME_DEV:/var/www
    - sudo docker start $PJ_DOCKER_NAME_DEV
