cache:
    key: ionportal
    paths:
    - node_modules/
stages:
    - compile
    - test
    - deploy
Compile:
    type: compile
    tags:
        - dev-docker
    only:
        - master
        - develop
        - raw
    script:
    - sudo docker exec local_mongo mongo ion --eval "db.dropDatabase()"
    - npm install
    - echo $'auth.denyTop=false\ndb.uri=mongodb://127.0.0.1:27017/ion\ndb.name=ion\ndb.user=root\ndb.pwd=ION-sql1\nserver.port1=8888\nserver.port2=8889\nserver.port3=3000\nmodule.default=registry\nfs.storageRoot=./files\nfs.urlBase=/files' > config/config.ini
    - export NODE_PATH=`pwd -P`
    - gulp install
    artifacts:
        name: "$CI_BUILD_STAGE_$CI_BUILD_REF_NAME"
        expire_in: 20 min
        untracked: true
Testing:
  type: test
  tags:
    - dev-selenium
  only:
        - master
        - develop
        - raw
  script:
    - C:\MongoDB\bin\mongo ion --eval "db.dropDatabase()"
    - $env:NODE_ENV = "development"
    - $env:NODE_PATH = pwd
    - $env:DEBUG = "ION:*"
    - npm install
    - gulp setup
    - start-job -ScriptBlock {node bin/www} -InitializationScript {cd "$Env:RUNNER_PATH\$Env:CI_PROJECT_DIR"} -Name $Env:PJ_DOCKER_NAME_DEV
."http://docker.local:Random platforma":
  type: deploy
  tags:
    - dev-docker
  only:
        - master
        - develop
        - raw
  script:
    - sudo docker stop $PJ_DOCKER_NAME$CI_BUILD_REF_NAME || true
    - sudo docker rm $PJ_DOCKER_NAME$CI_BUILD_REF_NAME || true
    - sudo docker run --name $PJ_DOCKER_NAME$CI_BUILD_REF_NAME -d -e NODE_PATH=/var/www -e DEBUG=ION:* -e NODE_ENV=development -p 8888 -p 22 iondvww supervisord
    - export DEBUG=ION:*
    - sudo docker cp ../platform $PJ_DOCKER_NAME$CI_BUILD_REF_NAME:/var/www
    - sudo docker exec $PJ_DOCKER_NAME$CI_BUILD_REF_NAME bash -c 'sleep 3 && node /var/www/bin/import.js'
    - sudo docker restart $PJ_DOCKER_NAME$CI_BUILD_REF_NAME
    - "curl -X POST -F token=$DevAndTestToken -F ref=$CI_BUILD_REF_NAME https://git.iondv.ru/api/v3/projects/34/trigger/builds"
    - sudo docker port $PJ_DOCKER_NAME$CI_BUILD_REF_NAME 8888 | sed -r 's/'0.0.0.0'+/http:\/\/192.168.0.228/g'